// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OurDecor;

#nullable disable

namespace OurDecor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301182824_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaterialTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Metering")
                        .HasColumnType("text");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("NameMaterial")
                        .HasColumnType("text");

                    b.Property<int>("QuantityPackage")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityStock")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeMaterial")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialTypeImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Mariage")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialType");
                });

            modelBuilder.Entity("OurDecor.Models.ProductMaterialsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductsImportId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityMaterial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProductsImportId");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("OurDecor.Models.ProductTypeImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoefficentProduct")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinPricePartner")
                        .HasColumnType("numeric");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeProduct")
                        .HasColumnType("text");

                    b.Property<decimal>("WidthRoll")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OurDecor.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OurDecor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.HasOne("OurDecor.Models.MaterialTypeImport", "MaterialType")
                        .WithMany("MaterialImports")
                        .HasForeignKey("MaterialTypeId");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("OurDecor.Models.ProductMaterialsImport", b =>
                {
                    b.HasOne("OurDecor.Models.MaterialImport", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurDecor.Models.ProductsImport", "Product")
                        .WithMany("ProductMaterialsImports")
                        .HasForeignKey("ProductsImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.HasOne("OurDecor.Models.ProductTypeImport", "ProductType")
                        .WithMany("ProductsImports")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("OurDecor.Models.User", b =>
                {
                    b.HasOne("OurDecor.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialTypeImport", b =>
                {
                    b.Navigation("MaterialImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductTypeImport", b =>
                {
                    b.Navigation("ProductsImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.Navigation("ProductMaterialsImports");
                });

            modelBuilder.Entity("OurDecor.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
