// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OurDecor;

#nullable disable

namespace OurDecor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307091637_migrationDataProduct")]
    partial class migrationDataProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaterialTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Metering")
                        .HasColumnType("text");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("NameMaterial")
                        .HasColumnType("text");

                    b.Property<int>("QuantityPackage")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityStock")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeMaterial")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialTypeImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Mariage")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeMaterial")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mariage = 0.7m,
                            TypeMaterial = "Бумага"
                        },
                        new
                        {
                            Id = 2,
                            Mariage = 0.5m,
                            TypeMaterial = "Краска"
                        },
                        new
                        {
                            Id = 3,
                            Mariage = 0.15m,
                            TypeMaterial = "Клей"
                        },
                        new
                        {
                            Id = 4,
                            Mariage = 0.2m,
                            TypeMaterial = "Дисперсия"
                        });
                });

            modelBuilder.Entity("OurDecor.Models.ProductMaterialsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("NameMaterial")
                        .HasColumnType("text");

                    b.Property<string>("Products")
                        .HasColumnType("text");

                    b.Property<int>("ProductsImportId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityMaterial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProductsImportId");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("OurDecor.Models.ProductTypeImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoefficentProduct")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeProduct")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoefficentProduct = 5.5m,
                            TypeProduct = "Декоративные обои"
                        },
                        new
                        {
                            Id = 2,
                            CoefficentProduct = 7.54m,
                            TypeProduct = "Фотообои"
                        },
                        new
                        {
                            Id = 3,
                            CoefficentProduct = 3.25m,
                            TypeProduct = "Обои под покрску"
                        },
                        new
                        {
                            Id = 4,
                            CoefficentProduct = 2.5m,
                            TypeProduct = "Cntrkjj,jb"
                        });
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinPricePartner")
                        .HasColumnType("numeric");

                    b.Property<string>("NameProduct")
                        .HasColumnType("text");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeProduct")
                        .HasColumnType("text");

                    b.Property<decimal>("WidthRoll")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Article = 1549922,
                            MinPricePartner = 16950.00m,
                            NameProduct = "Фотообои флизелиновые Горы 500x270 см",
                            TypeProduct = "Фотообои",
                            WidthRoll = 0.91m
                        },
                        new
                        {
                            Id = 4,
                            Article = 2018556,
                            MinPricePartner = 15850.00m,
                            NameProduct = "Обои из природного материала Традиционный принт светло",
                            TypeProduct = "Декоративные обои",
                            WidthRoll = 0.5m
                        },
                        new
                        {
                            Id = 5,
                            Article = 3028272,
                            MinPricePartner = 11430.00m,
                            NameProduct = "Обои под покраску флизелиновые Рельеф",
                            TypeProduct = "Обои под покраску",
                            WidthRoll = 0.75m
                        },
                        new
                        {
                            Id = 6,
                            Article = 4029272,
                            MinPricePartner = 5630.00m,
                            NameProduct = "Стеклообои Рогожка белые",
                            TypeProduct = "Стеклообои",
                            WidthRoll = 0.3m
                        },
                        new
                        {
                            Id = 7,
                            Article = 2118827,
                            MinPricePartner = 16200.00m,
                            NameProduct = "Обои флизелиновые Эвелин светло-серые",
                            TypeProduct = "Декоративные обои",
                            WidthRoll = 1.06m
                        },
                        new
                        {
                            Id = 8,
                            Article = 1758375,
                            MinPricePartner = 13500.00m,
                            NameProduct = "Обои под покраску флизелиновые цвет белый",
                            TypeProduct = "Обои под покраску",
                            WidthRoll = 0.68m
                        });
                });

            modelBuilder.Entity("OurDecor.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameRole = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            NameRole = "User"
                        });
                });

            modelBuilder.Entity("OurDecor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.HasOne("OurDecor.Models.MaterialTypeImport", "MaterialType")
                        .WithMany("MaterialImports")
                        .HasForeignKey("MaterialTypeId");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("OurDecor.Models.ProductMaterialsImport", b =>
                {
                    b.HasOne("OurDecor.Models.MaterialImport", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurDecor.Models.ProductsImport", "Product")
                        .WithMany("ProductMaterialsImports")
                        .HasForeignKey("ProductsImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.HasOne("OurDecor.Models.ProductTypeImport", "ProductType")
                        .WithMany("ProductsImports")
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("OurDecor.Models.User", b =>
                {
                    b.HasOne("OurDecor.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialTypeImport", b =>
                {
                    b.Navigation("MaterialImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductTypeImport", b =>
                {
                    b.Navigation("ProductsImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.Navigation("ProductMaterialsImports");
                });

            modelBuilder.Entity("OurDecor.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
