// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OurDecor;

#nullable disable

namespace OurDecor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Metering")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityPackage")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityStock")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("MaterialImport");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialTypeImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Mariage")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypeImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductMaterialsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityMaterial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("ProductMaterialsImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductTypeImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoefficentProduct")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypeImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinPricePartner")
                        .HasColumnType("numeric");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WidthRoll")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductsImports");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.HasOne("OurDecor.Models.MaterialTypeImport", "MaterialType")
                        .WithMany("MaterialImports")
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("OurDecor.Models.ProductMaterialsImport", b =>
                {
                    b.HasOne("OurDecor.Models.MaterialImport", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("OurDecor.Models.ProductsImport", b =>
                {
                    b.HasOne("OurDecor.Models.ProductTypeImport", "ProductType")
                        .WithMany("ProductsImports")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialImport", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("OurDecor.Models.MaterialTypeImport", b =>
                {
                    b.Navigation("MaterialImports");
                });

            modelBuilder.Entity("OurDecor.Models.ProductTypeImport", b =>
                {
                    b.Navigation("ProductsImports");
                });
#pragma warning restore 612, 618
        }
    }
}
